user:
 username: zhangsan
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

---
spring:
  profiles: windows
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

---
spring:
  profiles: mac
MAC_IP: 192.168.31.193
MAC_PORT: 8080
eureka:
  client:
    service-url:
      defaultZone: http://${MAC_IP}:${MAC_PORT}/eureka/
